export const SIGN_UP_ONE = 'SIGN_UP_ONE'
export const SIGN_UP = 'SIGN_UP'
export const LOGIN = 'LOGIN'
export const JOBSEARCH = 'JOBSEARCH'
export const POSTJOB = 'POSTJOB'
export const GET_ERRORS = 'GET_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const USERSEARCH = 'USERSEARCH'
export const USERSEARCHCONNECTION = 'USERSEARCHCONNECTION'
export const USERSEARCHCONREQUEST = 'USERSEARCHCONREQUEST'
export const USERSEARCHCONREQUESTREC = 'USERSEARCHCONREQUESTREC'




